import Head from "next/head"
import Main from "../components/main/Main.jsx"

export default function Home() {
  return (
    <div>
      <Head>
        <title>E-commerce CMS System</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Main />
      </main>
      <footer></footer>
    </div>
  )
}
